<?php $this->layout('layouts/admin', [
    'title' => 'Admin - Users',
]); ?>

<?php $this->section('content') ?>
<ol class="breadcrumb">
    <li><a href="/admin"><?= $this->translate('admin') ?></a></li>
    <li class="active"><?= $this->translate('users') ?></li>
</ol>

<table class="table table-striped">
    <tr>
        <th><?= $this->translate('first_name') ?></th>
        <th><?= $this->translate('last_name') ?></th>
        <th><?= $this->translate('role') ?></th>
        <th><?= $this->translate('email') ?></th>
        <th><?= $this->translate('created') ?></th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->users as $user): ?>
        <tr>
            <td><?= $user->first_name  ?></td>
            <td><?= $user->last_name  ?></td>
            <td><?= $user->role  ?></td>
            <td><?= $user->email  ?></td>
            <td><?= $user->created_at  ?></td>
            <td width="10%" class="text-right">
                <form id="deleteUser" method="POST" action="/admin/users/<?= $user->id  ?>">
                    <input type="hidden" name="_METHOD" value="DELETE">
                </form>
                <a href="/admin/users/<?= $user->id  ?>/edit"><?= $this->translate('edit') ?></a> |
                <a href="#" onclick="$('form#deleteUser').submit(); return false;"><?= $this->translate('delete') ?></a>
            </td>
        </tr>
    <?php endforeach ?>
</table>

<nav>
    <ul class="pagination">
        <li>
            <a href="#" aria-label="<?= $this->translate('previous') ?>">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li>
            <a href="#" aria-label="<?= $this->translate('next') ?>">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>
<?php $this->replace() ?>
