<?php $this->layout('layouts/admin', [
    'title' => 'Admin - Users - Edit',
]); ?>

<?php $this->section('content') ?>
    <ol class="breadcrumb">
        <li><a href="/admin"><?= $this->translate('admin') ?></a></li>
        <li><a href="/admin/users"><?= $this->translate('users') ?></a></li>
        <li class="active"><?= $this->translate('admin_users_edit_link') ?></li>
    </ol>

    <form method="post" action="/admin/users/<?= $this->user->id ?>">
        <div class="form-group">
            <label for="first_name"><?= $this->translate('first_name') ?></label>
            <input type="text" value="<?= $this->user->first_name ?>" class="form-control" name="first_name" id="first_name" placeholder="<?= $this->translate('first_name') ?>">
        </div>
        <div class="form-group">
            <label for="last_name"><?= $this->translate('last_name') ?></label>
            <input type="text" value="<?= $this->user->last_name ?>" class="form-control" name="last_name" id="last_name" placeholder="<?= $this->translate('last_name') ?>">
        </div>
        <div class="form-group">
            <label for="role"><?= $this->translate('role') ?></label>
            <select name="role" id="role" class="form-control">
                <option value="member" <?php if ($this->user->isContributor()): ?> selected="selected" <?php endif ?>><?= $this->translate('contributor') ?></option>
                <option value="editor" <?php if ($this->user->isEditor()): ?>  selected="selected" <?php endif ?>><?= $this->translate('editor') ?></option>
                <option value="admin" <?php if ($this->user->isAdmin()): ?> selected="selected" <?php endif ?>><?= $this->translate('admin') ?></option>
            </select>
        </div>
        <div class="form-group">
            <label for="description"><?= $this->translate('description') ?></label>
            <textarea id="description" name="description" class="form-control" rows="5"><?= $this->user->description ?></textarea>
        </div>
        <div class="form-group">
            <label for="email"><?= $this->translate('email') ?></label>
            <input type="email" value="<?= $this->user->email ?>" class="form-control" name="email" id="email" placeholder="Email">
        </div>

        <input type="hidden" name="_METHOD" value="PUT">

        <button type="submit" class="btn btn-primary"><?= $this->translate('save') ?></button>
        <a href="/admin/users" class="btn btn-default"><?= $this->translate('cancel') ?></a>
    </form>
<?php $this->replace() ?>
