<?php $this->layout('layouts/main'); ?>

<?php $this->section('content') ?>
    <h1>Register</h1>

    <div class="col-sm-6 col-sm-offset-3 sso-register">
        <div class="row">
        	<div class="col-xs-12">
                <div class="well">
                    <form method="post" action="/auth/register">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="first_name" class="sr-only"><?= $this->translate('common_first_name') ?></label>
                                    <input type="text" class="form-control" name="first_name" placeholder="<?= $this->translate('common_first_name') ?>" value="<?= $this->user->first_name ?>">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="last_name" class="sr-only"><?= $this->translate('common_last_name') ?></label>
                                    <input type="text" class="form-control" name="last_name" placeholder="<?= $this->translate('common_last_name') ?>" value="<?= $this->user->last_name ?>">
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="email" class="sr-only"><?= $this->translate('common_email') ?></label>
                            <input type="text" class="form-control" name="email" placeholder="<?= $this->translate('common_email') ?>" value="<?= $this->user->email ?>">
                        </div>

                        <div class="form-group">
                            <label for="password" class="sr-only"><?= $this->translate('common_password') ?></label>
                            <input type="password" class="form-control" name="password" placeholder="<?= $this->translate('common_password') ?>" value="">
                        </div>

                        <label class="checkbox-inline agreement">
                            <input name="agreement" type="checkbox"> <?= $this->translate('have_read_terms_conditions') ?>
                        </label>

                        <input type="text" class="more_info" name="more_info" value="" style="position: absolute; left: -9999px">

                        <?= $this->insert('partials/csrf_token') ?>

                        <hr>

                        <div class="row">
                            <div class="col-sm-6">
                                <button type="submit" class="btn btn-lg btn-block btn-primary"><?= $this->translate('register') ?></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<?php $this->replace() ?>
